
%% generated by soap from: /Users/szubtsovskiy/Projects/pragprog-elixir/15/events/http:/www.webservicex.net/CurrencyConvertor.asmx?WSDL
%% for service "CurrencyConvertor" and port "CurrencyConvertorSoap"
%% using options: [{service,"CurrencyConvertor"},{port,"CurrencyConvertorSoap"},{generate,client},{namespaces,[{"http://www.webserviceX.NET/","P0"}]},{generate_tests,client},{http_client,soap_client_inets},{client_name,"CurrencyConvertor.asmx?WSDL_client"},{strict,true}]

%%% This file contains record and type decarations that are used by the WSDL.
%%%
%%% It also contains a macro 'INTERFACE' that is used to make information
%%% about the WSDL available to the SOAP implementation.
%%%
%%% It is possible (and in some cases necessary) to change the name of the
%%% record fields.
%%%
%%% It is possible to add default values, but be aware that these will only
%%% be used when *writing* an xml document.

%%% Records used to represent fault response messages:

-record(faultdetail, {uri :: string(),
                      tag :: string(),
                      text :: string()}).

-record(faultcode, {uri :: string(),
                    code :: string(),
                    subcode :: #faultcode{} % only v. 1.2
                   }).

-record(faultreason, {text :: string(),
                      language :: string()}).

-record(soap_fault_1_1, {faultcode :: #faultcode{},
                         faultstring :: string(),
                         faultactor :: string(),
                         detail :: [#faultdetail{}]}).

-record(soap_fault_1_2, {code :: #faultcode{},
                         reason :: [#faultreason{}],
                         role :: string(),
                         detail :: [#faultdetail{}]}).

%% xsd:QName values are translated to #qname{} records.
-record(qname, {uri :: string(),
                localPart :: string(),
                prefix :: string(),
                mappedPrefix :: string()}).



-record('P0:double', {
	double :: float() | 'NaN' | 'INF' | '-INF'}).

-type 'P0:double'() :: #'P0:double'{}.


-record('P0:ConversionRateResponse', {
	'ConversionRateResult' :: float() | 'NaN' | 'INF' | '-INF'}).

-type 'P0:ConversionRateResponse'() :: #'P0:ConversionRateResponse'{}.


-record('P0:ConversionRate', {
	'FromCurrency' :: string(),
	'ToCurrency' :: string()}).

-type 'P0:ConversionRate'() :: #'P0:ConversionRate'{}.
-define(INTERFACE, {interface,"CurrencyConvertor",
                    'CurrencyConvertor.asmx?WSDL','1.1',soap_client_inets,
                    soap_server_cowboy_1,undefined,
                    'CurrencyConvertor.asmx?WSDL_client',[],
                    "http://www.webserviceX.NET/",
                    "http://schemas.xmlsoap.org/soap/envelope/",undefined,
                    undefined,
                    "http://www.webservicex.net/CurrencyConvertor.asmx",
                    "CurrencyConvertorSoap","CurrencyConvertorSoap",
                    "CurrencyConvertorSoap",
                    [{op,"ConversionRate",'ConversionRate',
                      "http://www.webserviceX.NET/ConversionRate",undefined,
                      request_response,'P0:ConversionRate',
                      'P0:ConversionRateResponse',undefined}],
                    {model,
                     [{type,'_document',sequence,
                       [{el,
                         [{alt,'P0:ConversionRate','P0:ConversionRate',[],1,
                           1,true,undefined},
                          {alt,'P0:ConversionRateResponse',
                           'P0:ConversionRateResponse',[],1,1,true,undefined},
                          {alt,'P0:double','P0:double',[],1,1,simple,
                           undefined}],
                         1,1,undefined,2}],
                       [],undefined,undefined,1,1,1,false,undefined},
                      {type,'P0:double',sequence,
                       [{el,
                         [{alt,'P0:double',
                           {'#PCDATA',float},
                           [],1,1,true,undefined}],
                         1,1,undefined,2}],
                       [],undefined,undefined,2,1,1,false,undefined},
                      {type,'P0:ConversionRateResponse',sequence,
                       [{el,
                         [{alt,'P0:ConversionRateResult',
                           {'#PCDATA',float},
                           [],1,1,true,undefined}],
                         1,1,undefined,2}],
                       [],undefined,undefined,2,1,1,undefined,undefined},
                      {type,'P0:ConversionRate',sequence,
                       [{el,
                         [{alt,'P0:FromCurrency',
                           {'#PCDATA',char},
                           [],1,1,true,undefined}],
                         1,1,undefined,2},
                        {el,
                         [{alt,'P0:ToCurrency',
                           {'#PCDATA',char},
                           [],1,1,true,undefined}],
                         1,1,undefined,3}],
                       [],undefined,undefined,3,1,1,undefined,undefined}],
                     [{ns,"http://www.w3.org/2001/XMLSchema","xsd",qualified},
                      {ns,"http://www.webserviceX.NET/","P0",qualified}],
                     "http://www.webserviceX.NET/",[],false,skip},
                    1,undefined,
                    [{"http://www.webserviceX.NET/","P0"}]}).
