%% generated by soap from: /Users/szubtsovskiy/Projects/pragprog-elixir/15/events/http:/www.webservicex.net/CurrencyConvertor.asmx?WSDL
%% for service "CurrencyConvertor" and port "CurrencyConvertorSoap"
%% using options: [{service,"CurrencyConvertor"},{port,"CurrencyConvertorSoap"},{generate,client},{namespaces,[{"http://www.webserviceX.NET/","P0"}]},{generate_tests,client},{http_client,soap_client_inets},{client_name,"CurrencyConvertor.asmx?WSDL_client"},{strict,true}]

-module('CurrencyConvertor.asmx?WSDL_client').

-include("CurrencyConvertor.asmx?WSDL.hrl").

-export([interface/0]).

%% The functions that are described by the WSDL
-export(['ConversionRate'/3]).

-spec 'ConversionRate'(Soap_body::'P0:ConversionRate'(),
  Soap_headers::[soap:soap_header()],
  Options::[any()]) -> soap:soap_response('P0:ConversionRateResponse'()).
'ConversionRate'(Soap_body, Soap_headers, Options) ->
  soap_client_util:call(Soap_body, Soap_headers, Options, "\"http://www.webserviceX.NET/ConversionRate\"", interface()).

%%% --------------------------------------------------------------------
%%% Internal functions
%%% --------------------------------------------------------------------
interface() ->
    ?INTERFACE.